# Generated by Django 3.2 on 2023-01-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genres',
        ),
    ]
