# Generated by Django 3.2.16 on 2023-01-21 19:52

from django.db import migrations, models
import django.db.models.deletion
import reviews.validations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_title_сategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='reviews.сategories'),
        ),
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(related_name='genres', to='reviews.Genres'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[reviews.validations.ValidateYear]),
        ),
    ]
