# Generated by Django 3.2.16 on 2023-01-21 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230121_2252'),
        ('reviews', '0005_alter_review_score'),
    ]

    operations = [
    ]
