# Generated by Django 3.2.16 on 2023-01-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_merge_0004_auto_20230121_2252_0005_alter_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(),
        ),
    ]
